/**
 * Supabase Database Types — Auto-generated via `supabase gen types typescript --linked`
 * Re-generate with: SUPABASE_ACCESS_TOKEN=<token> npx supabase gen types typescript --linked
 */

// ============================================================================
// Domain types (game-specific, not generated by Supabase)
// ============================================================================

export type GameMode = 'endless' | 'blitz' | 'daily' | 'duo';
export type PlayerRank = 'Bronce' | 'Plata' | 'Oro' | 'Platino' | 'Diamante';
export type SkillLevel = 'Novice' | 'Explorer' | 'Master' | 'Legend' | 'Infinite';
export type ItemType = 'skin' | 'power_up';
export type GridSize = 4 | 5 | 6;
export type NeonColor = '#00f5d4' | '#f72585' | '#ffd166' | '#7b2fff';

export interface PatternSequenceItem {
  cell: number;
  color: NeonColor;
  displayTime: number;
}

export interface PatternData {
  sequence: PatternSequenceItem[];
  totalCells: number;
  estimatedDifficulty: number;
  reasoning: string;
}

// ============================================================================
// Supabase generated types
// ============================================================================

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.4"
  }
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      daily_challenge_attempts: {
        Row: {
          challenge_id: string
          completed: boolean
          created_at: string
          id: string
          player_id: string
          score: number
        }
        Insert: {
          challenge_id: string
          completed?: boolean
          created_at?: string
          id?: string
          player_id: string
          score?: number
        }
        Update: {
          challenge_id?: string
          completed?: boolean
          created_at?: string
          id?: string
          player_id?: string
          score?: number
        }
        Relationships: [
          {
            foreignKeyName: "daily_challenge_attempts_challenge_id_fkey"
            columns: ["challenge_id"]
            isOneToOne: false
            referencedRelation: "daily_challenges"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "daily_challenge_attempts_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      daily_challenges: {
        Row: {
          attempts: number
          created_at: string
          date: string
          difficulty: number
          id: string
          pattern: Json
        }
        Insert: {
          attempts?: number
          created_at?: string
          date: string
          difficulty?: number
          id?: string
          pattern: Json
        }
        Update: {
          attempts?: number
          created_at?: string
          date?: string
          difficulty?: number
          id?: string
          pattern?: Json
        }
        Relationships: []
      }
      player_items: {
        Row: {
          acquired_at: string
          id: string
          item_id: string
          item_type: string
          player_id: string
          quantity: number
        }
        Insert: {
          acquired_at?: string
          id?: string
          item_id: string
          item_type: string
          player_id: string
          quantity?: number
        }
        Update: {
          acquired_at?: string
          id?: string
          item_id?: string
          item_type?: string
          player_id?: string
          quantity?: number
        }
        Relationships: [
          {
            foreignKeyName: "player_items_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          avg_response_ms: number | null
          created_at: string
          echoes: number
          games_played: number
          id: string
          rank: string
          skill_level: string
          total_xp: number
          updated_at: string
          username: string
        }
        Insert: {
          avatar_url?: string | null
          avg_response_ms?: number | null
          created_at?: string
          echoes?: number
          games_played?: number
          id: string
          rank?: string
          skill_level?: string
          total_xp?: number
          updated_at?: string
          username: string
        }
        Update: {
          avatar_url?: string | null
          avg_response_ms?: number | null
          created_at?: string
          echoes?: number
          games_played?: number
          id?: string
          rank?: string
          skill_level?: string
          total_xp?: number
          updated_at?: string
          username?: string
        }
        Relationships: []
      }
      friendships: {
        Row: {
          id: string
          requester_id: string
          addressee_id: string
          status: string
          created_at: string
        }
        Insert: {
          id?: string
          requester_id: string
          addressee_id: string
          status?: string
          created_at?: string
        }
        Update: {
          id?: string
          requester_id?: string
          addressee_id?: string
          status?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "friendships_requester_id_fkey"
            columns: ["requester_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "friendships_addressee_id_fkey"
            columns: ["addressee_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      analytics_events: {
        Row: {
          id: string
          event_type: string
          event_data: Json
          platform: string
          created_at: string
        }
        Insert: {
          id?: string
          event_type: string
          event_data?: Json
          platform?: string
          created_at?: string
        }
        Update: {
          id?: string
          event_type?: string
          event_data?: Json
          platform?: string
          created_at?: string
        }
        Relationships: []
      }
      scores: {
        Row: {
          cells_hit: number
          created_at: string
          duration_ms: number
          grid_size: number
          id: string
          max_combo: number
          mode: string
          player_id: string
          score: number
        }
        Insert: {
          cells_hit?: number
          created_at?: string
          duration_ms?: number
          grid_size?: number
          id?: string
          max_combo?: number
          mode: string
          player_id: string
          score: number
        }
        Update: {
          cells_hit?: number
          created_at?: string
          duration_ms?: number
          grid_size?: number
          id?: string
          max_combo?: number
          mode?: string
          player_id?: string
          score?: number
        }
        Relationships: [
          {
            foreignKeyName: "scores_player_id_fkey"
            columns: ["player_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      increment_daily_attempts: {
        Args: { challenge_date: string }
        Returns: undefined
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {},
  },
} as const
