-- ============================================================================
-- EchoShift — Initial Database Schema
-- ============================================================================
-- Run this in the Supabase SQL Editor (Dashboard > SQL Editor > New query)
-- Prerequisites: Supabase project with Auth enabled
-- ============================================================================

-- ============================================================================
-- 1. PROFILES — Player profiles linked to Supabase Auth
-- ============================================================================
CREATE TABLE profiles (
  id          UUID PRIMARY KEY REFERENCES auth.users ON DELETE CASCADE,
  username    TEXT UNIQUE NOT NULL,
  avatar_url  TEXT,
  rank        TEXT NOT NULL DEFAULT 'Bronce'
              CHECK (rank IN ('Bronce', 'Plata', 'Oro', 'Platino', 'Diamante')),
  total_xp    INTEGER NOT NULL DEFAULT 0 CHECK (total_xp >= 0),
  echoes      INTEGER NOT NULL DEFAULT 100 CHECK (echoes >= 0),
  skill_level TEXT NOT NULL DEFAULT 'Novice'
              CHECK (skill_level IN ('Novice', 'Explorer', 'Master', 'Legend', 'Infinite')),
  avg_response_ms INTEGER DEFAULT NULL,
  games_played INTEGER NOT NULL DEFAULT 0 CHECK (games_played >= 0),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE profiles IS 'Player profiles, one per auth.user';
COMMENT ON COLUMN profiles.echoes IS 'In-game currency, starts at 100';
COMMENT ON COLUMN profiles.rank IS 'Visible rank: Bronce→Plata→Oro→Platino→Diamante';
COMMENT ON COLUMN profiles.skill_level IS 'Internal skill tier based on avg response time';

-- ============================================================================
-- 2. SCORES — Game scores per mode
-- ============================================================================
CREATE TABLE scores (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  player_id   UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  mode        TEXT NOT NULL CHECK (mode IN ('endless', 'blitz', 'daily', 'duo')),
  score       INTEGER NOT NULL CHECK (score >= 0),
  max_combo   INTEGER NOT NULL DEFAULT 0 CHECK (max_combo >= 0),
  cells_hit   INTEGER NOT NULL DEFAULT 0 CHECK (cells_hit >= 0),
  duration_ms INTEGER NOT NULL DEFAULT 0 CHECK (duration_ms >= 0),
  grid_size   INTEGER NOT NULL DEFAULT 4 CHECK (grid_size IN (4, 5, 6)),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE scores IS 'Individual game scores across all modes';

-- ============================================================================
-- 3. DAILY_CHALLENGES — One pattern per day, same for all players
-- ============================================================================
CREATE TABLE daily_challenges (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  date        DATE UNIQUE NOT NULL,
  pattern     JSONB NOT NULL,
  difficulty  INTEGER NOT NULL DEFAULT 5 CHECK (difficulty BETWEEN 1 AND 10),
  attempts    INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE daily_challenges IS 'Daily challenge patterns generated by Claude API';
COMMENT ON COLUMN daily_challenges.pattern IS 'JSON: {sequence, totalCells, estimatedDifficulty, reasoning}';

-- ============================================================================
-- 4. DAILY_CHALLENGE_ATTEMPTS — Track per-player daily attempts (max 3/day)
-- ============================================================================
CREATE TABLE daily_challenge_attempts (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  player_id     UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  challenge_id  UUID NOT NULL REFERENCES daily_challenges(id) ON DELETE CASCADE,
  score         INTEGER NOT NULL DEFAULT 0 CHECK (score >= 0),
  completed     BOOLEAN NOT NULL DEFAULT FALSE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (player_id, challenge_id, created_at)
);

COMMENT ON TABLE daily_challenge_attempts IS 'Per-player attempts on daily challenges (max 3 per day)';

-- ============================================================================
-- 5. PLAYER_ITEMS — Owned items (skins, power-ups)
-- ============================================================================
CREATE TABLE player_items (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  player_id   UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  item_type   TEXT NOT NULL CHECK (item_type IN ('skin', 'power_up')),
  item_id     TEXT NOT NULL,
  quantity    INTEGER NOT NULL DEFAULT 1 CHECK (quantity >= 0),
  acquired_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (player_id, item_id)
);

COMMENT ON TABLE player_items IS 'Player inventory: skins and consumable power-ups';

-- ============================================================================
-- 6. INDEXES
-- ============================================================================

-- Scores: leaderboard queries (top scores per mode)
CREATE INDEX idx_scores_mode_score ON scores (mode, score DESC);

-- Scores: player history
CREATE INDEX idx_scores_player_id ON scores (player_id, created_at DESC);

-- Daily challenges: lookup by date
CREATE INDEX idx_daily_challenges_date ON daily_challenges (date);

-- Daily attempts: check attempt count per player per challenge
CREATE INDEX idx_daily_attempts_player_challenge
  ON daily_challenge_attempts (player_id, challenge_id);

-- Player items: inventory lookup
CREATE INDEX idx_player_items_player ON player_items (player_id);

-- Profiles: leaderboard by XP
CREATE INDEX idx_profiles_total_xp ON profiles (total_xp DESC);

-- ============================================================================
-- 7. UPDATED_AT TRIGGER
-- ============================================================================
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER profiles_updated_at
  BEFORE UPDATE ON profiles
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ============================================================================
-- 8. AUTO-CREATE PROFILE ON SIGNUP
-- ============================================================================
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, username)
  VALUES (
    NEW.id,
    COALESCE(
      NEW.raw_user_meta_data ->> 'username',
      'player_' || LEFT(NEW.id::TEXT, 8)
    )
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION handle_new_user();

-- ============================================================================
-- 9. ROW LEVEL SECURITY (RLS)
-- ============================================================================

-- Enable RLS on all tables
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE scores ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_challenges ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_challenge_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE player_items ENABLE ROW LEVEL SECURITY;

-- ---- PROFILES ----
-- Anyone can read profiles (for leaderboards)
CREATE POLICY "profiles_select_all"
  ON profiles FOR SELECT
  USING (true);

-- Users can only update their own profile
CREATE POLICY "profiles_update_own"
  ON profiles FOR UPDATE
  USING (auth.uid() = id)
  WITH CHECK (auth.uid() = id);

-- ---- SCORES ----
-- Anyone can read scores (leaderboards are public)
CREATE POLICY "scores_select_all"
  ON scores FOR SELECT
  USING (true);

-- Users can insert their own scores
CREATE POLICY "scores_insert_own"
  ON scores FOR INSERT
  WITH CHECK (auth.uid() = player_id);

-- ---- DAILY CHALLENGES ----
-- Anyone can read daily challenges
CREATE POLICY "daily_challenges_select_all"
  ON daily_challenges FOR SELECT
  USING (true);

-- Only service role can insert/update (server-side via SUPABASE_SERVICE_KEY)
-- No insert/update policy for anon/authenticated — handled by service role bypass

-- ---- DAILY CHALLENGE ATTEMPTS ----
-- Users can read their own attempts
CREATE POLICY "daily_attempts_select_own"
  ON daily_challenge_attempts FOR SELECT
  USING (auth.uid() = player_id);

-- Users can insert their own attempts
CREATE POLICY "daily_attempts_insert_own"
  ON daily_challenge_attempts FOR INSERT
  WITH CHECK (auth.uid() = player_id);

-- ---- PLAYER ITEMS ----
-- Users can read their own items
CREATE POLICY "player_items_select_own"
  ON player_items FOR SELECT
  USING (auth.uid() = player_id);

-- Users can insert their own items (purchases)
CREATE POLICY "player_items_insert_own"
  ON player_items FOR INSERT
  WITH CHECK (auth.uid() = player_id);

-- Users can update their own items (quantity changes)
CREATE POLICY "player_items_update_own"
  ON player_items FOR UPDATE
  USING (auth.uid() = player_id)
  WITH CHECK (auth.uid() = player_id);

-- ============================================================================
-- 10. HELPER FUNCTION: Increment daily challenge attempt count
-- ============================================================================
CREATE OR REPLACE FUNCTION increment_daily_attempts(challenge_date DATE)
RETURNS VOID AS $$
BEGIN
  UPDATE daily_challenges
  SET attempts = attempts + 1
  WHERE date = challenge_date;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
